# Global options
baseurl = "https://ucrl-iclr26.github.io/"
canonifyurls = true
languagecode = "en"
theme = "crl-uai-2022-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "Workshop on"
  title = "Unifying Concept Representation Learning"
  subtitle = "April 26-27 @ ICLR 2026"
  author = "Amit Dhurandhar, Amir-Hossein Karimi, Sara Magliacane, Stefano Teso, Efthymia Tsamoura, Zhe Zheng"
  description = "Workshop on Unifying Concept Representation Learning (ICLR 2026)"
  keywords = ["workshop", "concepts", "explainable AI", "neuro-symbolic AI", "causal representation learning"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "Call for Papers"
    url  = "/call-for-papers"
    weight = 1
[[menu.main]]
    name = "Dates"
    url  = "/dates"
    weight = 2
[[menu.main]]
    name = "Formatting Instructions"
    url  = "/formatting-instructions"
    weight = 3
[[menu.main]]
    name = "Organisers"
    url  = "/organisers-reviewers"
    weight = 4
[[menu.main]]
    name = "Accepted Papers"
    url  = "/accepted-papers"
    weight = 5
[[menu.main]]
    name = "Schedule and Format"
    url  = "/schedule-format"
    weight = 6
[[menu.main]]
    name = "Invited Speakers"
    url  = "/invited-speakers"
    weight = 7
